"""Birthday CRUD service — create, list, update, delete."""

from datetime import date
from typing import Optional

from sqlalchemy import and_, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.timezone import user_today
from app.models.birthday import Birthday
from app.models.reminder import Reminder, ReminderStatus
from app.models.user import User

BIRTHDAY_TITLE_PREFIX = "\U0001f382 "  # 🎂


def next_birthday_date(birth_date: date, today: date | None = None) -> date:
    """Calculate the next upcoming birthday from today."""
    if today is None:
        today = date.today()
    month, day = birth_date.month, birth_date.day
    for year in (today.year, today.year + 1):
        try:
            candidate = date(year, month, day)
        except ValueError:
            # Feb 29 in a non-leap year → fall back to Feb 28
            candidate = date(year, month, 28)
        if candidate >= today:
            return candidate
    return date(today.year + 1, month, min(day, 28))


def days_until(next_birthday: date, today: date | None = None) -> int:
    """Calculate days until the next birthday."""
    if today is None:
        today = date.today()
    return (next_birthday - today).days


async def create_birthday(
    db: AsyncSession,
    user: User,
    name: str,
    birth_date: date,
    birth_year: int | None = None,
    advance_days: int = 3,
    reminder_time=None,
) -> Birthday:
    from datetime import time as _time

    birthday = Birthday(
        user_id=user.id,
        name=name,
        birth_date=birth_date,
        birth_year=birth_year,
        advance_days=advance_days,
        reminder_time=reminder_time or _time(10, 0),
    )
    db.add(birthday)
    await db.commit()
    await db.refresh(birthday)
    return birthday


async def list_birthdays(
    db: AsyncSession,
    user: User,
) -> list[Birthday]:
    """List all birthdays for a user, sorted by next upcoming date."""
    today = await user_today(db, user.id)
    result = await db.execute(
        select(Birthday)
        .where(Birthday.user_id == user.id)
        .order_by(Birthday.birth_date)
    )
    birthdays = list(result.scalars().all())
    # Sort by next upcoming birthday date
    birthdays.sort(key=lambda b: next_birthday_date(b.birth_date, today=today))
    return birthdays


async def get_birthday(
    db: AsyncSession,
    birthday_id: int,
    user: User,
) -> Optional[Birthday]:
    result = await db.execute(
        select(Birthday).where(
            Birthday.id == birthday_id, Birthday.user_id == user.id
        )
    )
    return result.scalar_one_or_none()


async def _delete_pending_birthday_reminders(
    db: AsyncSession, user_id: int, name: str
) -> None:
    """Delete pending reminders generated by birthday scheduler for a given name."""
    title = f"{BIRTHDAY_TITLE_PREFIX}{name}"
    result = await db.execute(
        select(Reminder).where(
            and_(
                Reminder.user_id == user_id,
                Reminder.title == title,
                Reminder.status == ReminderStatus.pending,
            )
        )
    )
    for reminder in result.scalars().all():
        await db.delete(reminder)


async def update_birthday(
    db: AsyncSession,
    birthday_id: int,
    user: User,
    **kwargs: object,
) -> Optional[Birthday]:
    birthday = await get_birthday(db, birthday_id, user)
    if not birthday:
        return None

    old_name = birthday.name
    needs_reminder_reset = "advance_days" in kwargs or "name" in kwargs or "reminder_time" in kwargs

    for key, value in kwargs.items():
        setattr(birthday, key, value)

    if needs_reminder_reset:
        await _delete_pending_birthday_reminders(db, user.id, old_name)
        if "name" in kwargs and kwargs["name"] != old_name:
            await _delete_pending_birthday_reminders(db, user.id, kwargs["name"])

    await db.commit()
    await db.refresh(birthday)
    return birthday


async def delete_birthday(
    db: AsyncSession,
    birthday_id: int,
    user: User,
) -> bool:
    birthday = await get_birthday(db, birthday_id, user)
    if not birthday:
        return False
    await _delete_pending_birthday_reminders(db, user.id, birthday.name)
    await db.delete(birthday)
    await db.commit()
    return True
