"""add_proposal_subject_to_leads

Revision ID: 1d7947e37f69
Revises: 043
Create Date: 2026-04-01 18:53:29.986034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d7947e37f69'
down_revision: Union[str, None] = '043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('proposal_subject', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'proposal_subject')
    # ### end Alembic commands ###
