"""replace drive_file_id with prompt_instructions in industry

Revision ID: 42e6da138494
Revises: 042
Create Date: 2026-03-31 21:06:30.667416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e6da138494'
down_revision: Union[str, None] = '042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_event_links_event_id', table_name='task_event_links')
    op.drop_index('ix_task_event_links_task_id', table_name='task_event_links')
    op.drop_table('task_event_links')
    op.drop_constraint('google_oauth_tokens_user_id_key', 'google_oauth_tokens', type_='unique')
    op.drop_index('ix_google_oauth_tokens_user_id', table_name='google_oauth_tokens')
    op.create_index(op.f('ix_google_oauth_tokens_user_id'), 'google_oauth_tokens', ['user_id'], unique=True)
    op.add_column('industries', sa.Column('prompt_instructions', sa.Text(), nullable=True))
    op.drop_column('industries', 'drive_file_id')
    op.drop_index('ix_job_event_links_event_id', table_name='job_event_links')
    op.drop_index('ix_job_event_links_job_id', table_name='job_event_links')
    op.drop_index('ix_job_task_links_job_id', table_name='job_task_links')
    op.drop_index('ix_job_task_links_task_id', table_name='job_task_links')
    op.drop_index('ix_note_event_links_event_id', table_name='note_event_links')
    op.drop_index('ix_note_event_links_note_id', table_name='note_event_links')
    op.drop_index('ix_note_job_links_job_id', table_name='note_job_links')
    op.drop_index('ix_note_job_links_note_id', table_name='note_job_links')
    op.drop_index('ix_note_task_links_note_id', table_name='note_task_links')
    op.drop_index('ix_note_task_links_task_id', table_name='note_task_links')
    op.drop_constraint('uq_tags_user_name', 'tags', type_='unique')
    op.drop_index('ix_task_tags_tag_id', table_name='task_tags')
    op.drop_index('ix_user_profiles_user_id', table_name='user_profiles')
    op.drop_index('ix_user_settings_user_id', table_name='user_settings')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('ix_user_settings_user_id', 'user_settings', ['user_id'], unique=False)
    op.create_index('ix_user_profiles_user_id', 'user_profiles', ['user_id'], unique=True)
    op.create_index('ix_task_tags_tag_id', 'task_tags', ['tag_id'], unique=False)
    op.create_unique_constraint('uq_tags_user_name', 'tags', ['user_id', 'name'])
    op.create_index('ix_note_task_links_task_id', 'note_task_links', ['task_id'], unique=False)
    op.create_index('ix_note_task_links_note_id', 'note_task_links', ['note_id'], unique=False)
    op.create_index('ix_note_job_links_note_id', 'note_job_links', ['note_id'], unique=False)
    op.create_index('ix_note_job_links_job_id', 'note_job_links', ['job_id'], unique=False)
    op.create_index('ix_note_event_links_note_id', 'note_event_links', ['note_id'], unique=False)
    op.create_index('ix_note_event_links_event_id', 'note_event_links', ['event_id'], unique=False)
    op.create_index('ix_job_task_links_task_id', 'job_task_links', ['task_id'], unique=False)
    op.create_index('ix_job_task_links_job_id', 'job_task_links', ['job_id'], unique=False)
    op.create_index('ix_job_event_links_job_id', 'job_event_links', ['job_id'], unique=False)
    op.create_index('ix_job_event_links_event_id', 'job_event_links', ['event_id'], unique=False)
    op.add_column('industries', sa.Column('drive_file_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('industries', 'prompt_instructions')
    op.drop_index(op.f('ix_google_oauth_tokens_user_id'), table_name='google_oauth_tokens')
    op.create_index('ix_google_oauth_tokens_user_id', 'google_oauth_tokens', ['user_id'], unique=False)
    op.create_unique_constraint('google_oauth_tokens_user_id_key', 'google_oauth_tokens', ['user_id'])
    op.create_table('task_event_links',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.id'], name='task_event_links_event_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='task_event_links_task_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='task_event_links_pkey'),
    sa.UniqueConstraint('task_id', 'event_id', name='uq_task_event')
    )
    op.create_index('ix_task_event_links_task_id', 'task_event_links', ['task_id'], unique=False)
    op.create_index('ix_task_event_links_event_id', 'task_event_links', ['event_id'], unique=False)
    # ### end Alembic commands ###
