"""add floating urgent digest fields

Revision ID: 80ea5c1e77de
Revises: 3d99cd85a031
Create Date: 2026-04-07 16:44:46.338342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80ea5c1e77de'
down_revision: Union[str, None] = '3d99cd85a031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pulse_settings', sa.Column('digest_reminders_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('pulse_settings', sa.Column('digest_reminders_interval_hours', sa.Integer(), server_default='3', nullable=False))
    op.add_column('pulse_settings', sa.Column('digest_reminders_start_hour', sa.Integer(), server_default='7', nullable=False))
    op.add_column('pulse_settings', sa.Column('digest_reminders_end_hour', sa.Integer(), server_default='22', nullable=False))
    op.add_column('pulse_settings', sa.Column('last_reminder_digest_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reminders', sa.Column('is_floating', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('reminders', sa.Column('is_urgent', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'is_urgent')
    op.drop_column('reminders', 'is_floating')
    op.drop_column('pulse_settings', 'last_reminder_digest_at')
    op.drop_column('pulse_settings', 'digest_reminders_end_hour')
    op.drop_column('pulse_settings', 'digest_reminders_start_hour')
    op.drop_column('pulse_settings', 'digest_reminders_interval_hours')
    op.drop_column('pulse_settings', 'digest_reminders_enabled')
    # ### end Alembic commands ###
