"""add birthdays table and birthday pulse settings

Revision ID: 91e70bc8b5d3
Revises: 55d5e2acd495
Create Date: 2026-04-06 22:25:59.922468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91e70bc8b5d3'
down_revision: Union[str, None] = '55d5e2acd495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birthdays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('advance_days', sa.Integer(), server_default='3', nullable=False),
    sa.Column('reminder_time', sa.Time(), server_default='10:00:00', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_birthdays_user_id'), 'birthdays', ['user_id'], unique=False)
    op.add_column('pulse_settings', sa.Column('birthday_advance_days', sa.Integer(), server_default='3', nullable=False))
    op.add_column('pulse_settings', sa.Column('birthday_reminder_time', sa.Time(), server_default='10:00:00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pulse_settings', 'birthday_reminder_time')
    op.drop_column('pulse_settings', 'birthday_advance_days')
    op.drop_index(op.f('ix_birthdays_user_id'), table_name='birthdays')
    op.drop_table('birthdays')
    # ### end Alembic commands ###
