"""add_reminders_table_and_pulse_settings_fields

Revision ID: de5130692fc4
Revises: 046
Create Date: 2026-04-06 21:06:03.609603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de5130692fc4'
down_revision: Union[str, None] = '046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'done', name='reminderstatus'), nullable=False),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recurrence_rule', sa.String(length=20), nullable=True),
    sa.Column('snooze_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('notification_sent_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_remind_at'), 'reminders', ['remind_at'], unique=False)
    op.create_index('ix_reminders_remind_at_status', 'reminders', ['remind_at', 'status'], unique=False)
    op.create_index(op.f('ix_reminders_task_id'), 'reminders', ['task_id'], unique=False)
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    op.create_index('ix_reminders_user_status', 'reminders', ['user_id', 'status'], unique=False)
    op.add_column('pulse_settings', sa.Column('reminder_repeat_count', sa.Integer(), server_default='5', nullable=False))
    op.add_column('pulse_settings', sa.Column('reminder_repeat_interval', sa.Integer(), server_default='5', nullable=False))
    op.add_column('pulse_settings', sa.Column('reminder_snooze_limit', sa.Integer(), server_default='5', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pulse_settings', 'reminder_snooze_limit')
    op.drop_column('pulse_settings', 'reminder_repeat_interval')
    op.drop_column('pulse_settings', 'reminder_repeat_count')
    op.drop_index('ix_reminders_user_status', table_name='reminders')
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_task_id'), table_name='reminders')
    op.drop_index('ix_reminders_remind_at_status', table_name='reminders')
    op.drop_index(op.f('ix_reminders_remind_at'), table_name='reminders')
    op.drop_table('reminders')
    op.execute("DROP TYPE IF EXISTS reminderstatus")
    # ### end Alembic commands ###
