"""add instruction_outreach_industry

Revision ID: f270f7c9a854
Revises: 42e6da138494
Create Date: 2026-04-01 09:13:25.489762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f270f7c9a854'
down_revision: Union[str, None] = '42e6da138494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('instruction_outreach_industry', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'instruction_outreach_industry')
    # ### end Alembic commands ###
